const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1100,height:1500}});let external=[],errors=[];page.on('request',r=>{if(!r.url().startsWith('file:'))external.push(r.url());});page.on('pageerror',e=>errors.push(String(e)));
await page.goto(require('node:url').pathToFileURL(require('node:path').join(__dirname,'index.html')).href);await page.click('#sample');await page.click('#inspect');assert.match(await page.locator('#output h2').innerText(),/Unverified/);assert.equal(await page.locator('#output .result').count(),2);assert.match(await page.locator('#output').innerText(),/sender|fictional.example/);
await page.fill('#trusted','mx.fictional.example');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Selected reported results');
await page.fill('#trusted','wrong.example');assert.equal(await page.isChecked('#confirm'),false);assert.match(await page.locator('#output h2').innerText(),/Unverified/);
await page.fill('#raw','From: "bank@bank.example" <a@evil.example>\nReply-To: reply@bank.example\n\nAuthentication-Results: mx; spf=pass; dkim=pass; dmarc=pass');assert.equal(await page.locator('#output').isVisible(),false);await page.click('#inspect');assert.equal(await page.locator('#output .result').count(),0);assert.match(await page.locator('#output').innerText(),/evil.example/);
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx; dkim=fail reason="<img src=x onerror=alert(1)>"');await page.click('#inspect');assert.equal(await page.locator('#output img').count(),0);await page.locator('summary').click();assert.match(await page.locator('pre').innerText(),/<img/);
await page.click('#clear');assert.equal(await page.inputValue('#raw'),'');await page.click('#inspect');assert.match(await page.locator('#error').innerText(),/Paste/);
for(const raw of ['Name <<a@example.com>','A <"foo"bar@example.com>','A <a@exam"ple".com>']){
await page.fill('#raw','From: '+raw+'\nAuthentication-Results: mx.example.net; spf=pass');await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Unverified headers');assert.match(await page.locator('#output').innerText(),/unresolved/);
}
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx.example.net; unknown=pass this-is-malformed');await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Unverified headers');assert.match(await page.locator('#output').innerText(),/Unsupported authentication method/);assert.match(await page.locator('#output').innerText(),/Unsupported result property syntax/);
for(const suffix of ['bogus=thing','invalid!property=x','header.from=example.com=evil.example']){
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx.example.net; dkim=pass header.d=example.com '+suffix);await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Unverified headers');assert.match(await page.locator('#output').innerText(),/Unsupported result property syntax/);
}
for(const clause of ['dkim=fail reason="signature failed" header.d=example.com','dkim=pass header.d=example.com header.x-custom="extension value"']){
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx.example.net; '+clause);await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Selected reported results');
}
for(const clause of ['dkim=pass reason=a@b','dkim=pass header.i=foo..bar@example.com','dkim=pass header.i=a@-bad.example','dkim=pass header.i=a@example..com','dkim=pass header.x_bad=x']){
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx.example.net; '+clause);await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Unverified headers');assert.match(await page.locator('#output').innerText(),/Review:/);
}
for(const clause of ['dkim=pass reason="a@b"','dkim=pass header.i=foo.bar@example.com']){
await page.fill('#raw','From: a@example.com\nAuthentication-Results: mx.example.net; '+clause);await page.click('#inspect');await page.fill('#trusted','mx.example.net');await page.check('#confirm');await page.click('#apply');assert.equal(await page.locator('#output h2').innerText(),'Selected reported results');
}
await page.click('#sample');await page.click('#inspect');await page.screenshot({path:require('node:path').join(__dirname,'Desktop-QA.png'),fullPage:true});
await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:require('node:path').join(__dirname,'Mobile-QA.png'),fullPage:true});assert.deepEqual(external,[]);assert.deepEqual(errors,[]);console.log('PASS 28 browser checks (including all QA HOLD rounds): defaults, selection, reset, body boundary, address parsing, XSS text, clear, empty, mobile width, no external requests, no JS errors, actual shared parser loaded.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
