'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const H=require('./header-check.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const from='From: A <a@example.com>\n';
const good='Authentication-Results: mx.example.net; spf=pass smtp.mailfrom=example.com; dkim=pass header.d=example.com; dmarc=pass header.from=example.com\n';
const opts={index:0,trustedId:'mx.example.net',confirmedBoundary:true};
test('all pass never means safe or verified',()=>{const r=H.analyse(good+from);assert.equal(r.status,'unverified');assert.equal(r.verdict,undefined);});
test('explicit boundary shows reported results only',()=>{const r=H.analyse(good+from,opts);assert.equal(r.status,'selected');assert.equal(r.selected.results.length,3);});
test('cannot select by authserv-id alone',()=>assert.equal(H.analyse(good+from,{trustedId:opts.trustedId,index:0}).status,'unverified'));
test('confirmation without ID cannot select',()=>assert.equal(H.analyse(good+from,{confirmedBoundary:true,index:0}).status,'unverified'));
test('top none lower attacker pass not combined',()=>{const r=H.analyse('Authentication-Results: mx.example.net; spf=none; dkim=none; dmarc=none\n'+good.replace('mx.example.net','evil.example')+from,opts);assert.equal(r.selected.results.filter(x=>x.result==='pass').length,0);});
test('body header ignored',()=>{const r=H.analyse(from+'Subject: hi\n\n'+good,opts);assert.equal(r.reports.length,0);assert.equal(r.status,'unverified');});
test('quoted display name cannot hide actual domain',()=>{const r=H.analyse(good+'From: "help@bank.example" <attacker@evil.example>\nReply-To: help@bank.example');assert.equal(r.from.domain,'evil.example');assert.ok(r.notes.some(x=>x.includes('Reply-To')));});
test('duplicate provider ID unresolved',()=>assert.equal(H.analyse(good+good+from,opts).status,'unverified'));
test('known ID spoof still defaults unverified',()=>assert.equal(H.analyse(good.replace('mx.example.net','mx.google.com')+from).status,'unverified'));
test('wrong ID unresolved',()=>assert.equal(H.analyse(good+from,{...opts,trustedId:'other'}).status,'unverified'));
test('folded CRLF case insensitive',()=>{const r=H.analyse(good.replace(/; /g,';\r\n\t').replace('Authentication-Results','authentication-results')+from,opts);assert.equal(r.status,'selected');});
test('comments and quoted semicolons do not make fake clauses',()=>{const r=H.analyse('Authentication-Results: mx.example.net (comment; spf=pass); dkim=fail reason="x; dmarc=pass" header.d=example.com\n'+from,opts);assert.deepEqual(r.selected.results.map(x=>x.method),['dkim']);assert.equal(r.selected.results[0].result,'fail');});
test('SPF fail plus DMARC pass explained without safe verdict',()=>{const r=H.analyse(good.replace('spf=pass','spf=fail')+from,opts);assert.ok(r.notes.some(x=>x.includes('aligned')));assert.equal(r.verdict,undefined);});
test('duplicate From unresolved',()=>assert.equal(H.analyse(good+from+from,opts).status,'unverified'));
test('multiple From mailboxes unresolved',()=>assert.equal(H.analyse(good+'From: a@example.com, b@example.com',opts).status,'unverified'));
test('address group unresolved',()=>assert.equal(H.mailbox('Team: a@example.com;').domain,null));
test('comment email ignored in mailbox',()=>assert.equal(H.mailbox('a@evil.example (bank@bank.example)').domain,'evil.example'));
test('quoted local part deliberately unresolved',()=>assert.equal(H.mailbox('"odd local"@example.com').domain,null));
test('international mailbox deliberately unresolved',()=>assert.equal(H.mailbox('a@éxample.com').domain,null));
test('DMARC inconsistent with From unresolved',()=>assert.equal(H.analyse(good.replace('header.from=example.com','header.from=evil.example')+from,opts).status,'unverified'));
test('conflicting DMARC unresolved',()=>assert.equal(H.analyse(good.replace('header.from=example.com','header.from=example.com; dmarc=fail header.from=example.com')+from,opts).status,'unverified'));
test('unknown result unresolved',()=>assert.equal(H.analyse(good.replace('spf=pass','spf=superpass')+from,opts).status,'unverified'));
test('method version unresolved',()=>assert.equal(H.analyse(good.replace('spf=','spf/2=')+from,opts).status,'unverified'));
test('header version unresolved',()=>assert.equal(H.analyse(good.replace('mx.example.net;','mx.example.net 2;')+from,opts).status,'unverified'));
test('unclosed comment unresolved',()=>assert.equal(H.analyse(good.replace('spf=pass','spf=pass (oops')+from,opts).status,'unverified'));
test('duplicate properties unresolved',()=>assert.equal(H.analyse(good.replace('header.d=example.com','header.d=example.com header.d=evil.example')+from,opts).status,'unverified'));
test('orphan fold unresolved',()=>assert.equal(H.analyse(' orphan\n'+good+from,opts).status,'unverified'));
test('malformed header unresolved',()=>assert.equal(H.analyse('not a header\n'+good+from,opts).status,'unverified'));
test('ARC and Received-SPF not substitutes',()=>assert.equal(H.analyse('ARC-Authentication-Results: 1; '+good+from).reports.length,0));
test('empty rejected',()=>assert.throws(()=>H.analyse('')));
test('oversize rejected',()=>assert.throws(()=>H.analyse('x'.repeat(H.MAX+1))));
test('NUL rejected',()=>assert.throws(()=>H.analyse(from+'\0')));
test('fake angle address in display name ignored',()=>assert.equal(H.mailbox('"<help@bank.example>" <a@evil.example>').domain,'evil.example'));
test('malformed angle address unresolved',()=>assert.equal(H.mailbox('a@example.com>').domain,null));
test('repeated SPF requires review',()=>assert.equal(H.analyse(good.replace('spf=pass','spf=fail; spf=pass')+from,opts).status,'unverified'));
for(const address of ['Name <<a@example.com>','A <"foo"bar@example.com>','A <a@exam"ple".com>'])test('QA malformed mailbox '+address,()=>{assert.equal(H.mailbox(address).domain,null);assert.equal(H.analyse(good+'From: '+address,opts).status,'unverified');});
test('QA unknown malformed method cannot select',()=>{const r=H.analyse('Authentication-Results: mx.example.net; unknown=pass this-is-malformed\n'+from,opts);assert.equal(r.status,'unverified');assert.ok(r.selected.issues.length);});
test('unknown method versions and result tails reviewed',()=>{const r=H.auth('mx; unknown/2=superpass foo=bar broken',0);assert.ok(r.issues.length>=3);});
test('DKIM conflicting identity flagged',()=>{const r=H.analyse(good.replace('dkim=pass header.d=example.com','dkim=pass header.d=example.com; dkim=fail header.d=example.com')+from,opts);assert.ok(r.notes.some(x=>x.includes('conflicting DKIM')));});
for(const suffix of ['bogus=thing','invalid!property=x','header.from=example.com=evil.example'])test('QA property grammar '+suffix,()=>{const r=H.analyse('Authentication-Results: mx.example.net; dkim=pass header.d=example.com '+suffix+'\n'+from,opts);assert.equal(r.status,'unverified');assert.ok(r.selected.issues.length);});
test('valid reason before properties supported',()=>{const r=H.analyse('Authentication-Results: mx.example.net; dkim=fail reason="signature failed; needs review" header.d=example.com\n'+from,opts);assert.equal(r.status,'selected');assert.equal(r.selected.results[0].properties.reason,'signature failed; needs review');});
test('valid extension property supported',()=>{const r=H.analyse('Authentication-Results: mx.example.net; dkim=pass header.d=example.com header.x-custom="extension value"\n'+from,opts);assert.equal(r.status,'selected');assert.equal(r.selected.results[0].properties['header.x-custom'],'extension value');});
test('reason after property reviewed',()=>assert.equal(H.analyse('Authentication-Results: mx.example.net; dkim=pass header.d=example.com reason=x\n'+from,opts).status,'unverified'));
test('quoted value trailing garbage reviewed',()=>assert.equal(H.analyse('Authentication-Results: mx.example.net; dkim=pass header.d="example.com"evil\n'+from,opts).status,'unverified'));
for(const clause of ['dkim=pass reason=a@b','dkim=pass header.i=foo..bar@example.com','dkim=pass header.i=a@-bad.example','dkim=pass header.i=a@example..com','dkim=pass header.x_bad=x'])test('QA reason/identity/Keyword '+clause,()=>{const r=H.analyse('Authentication-Results: mx.example.net; '+clause+'\n'+from,opts);assert.equal(r.status,'unverified');assert.ok(r.selected.issues.length);});
for(const clause of ['dkim=pass reason="a@b"','dkim=pass header.i=foo.bar@example.com','dkim=pass header.i=@example.com'])test('valid reason/identity '+clause,()=>assert.equal(H.analyse('Authentication-Results: mx.example.net; '+clause+'\n'+from,opts).status,'selected'));
console.log(count+' parser regressions passed');
